webtalk_init -webtalk_dir /home/cedar/Documents/School/TAMU/2021/Autumn/ECEN 248/Laboratory Material/Lab 7/lab7/lab7.sim/sim_1/behav/xsim/xsim.dir/d_flip_flop_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct 27 22:58:23 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212050539_0_0_463" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "be5349e5-5b53-4f57-9941-c6cdaae86266" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fb5eb8cc9eea41ea8e1e9e58e7c2ea48" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX(tm)-8320 Eight-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1400.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "211 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115868_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1466153223 -regid "212050539_0_0_463" -xml /home/cedar/Documents/School/TAMU/2021/Autumn/ECEN 248/Laboratory Material/Lab 7/lab7/lab7.sim/sim_1/behav/xsim/xsim.dir/d_flip_flop_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/cedar/Documents/School/TAMU/2021/Autumn/ECEN 248/Laboratory Material/Lab 7/lab7/lab7.sim/sim_1/behav/xsim/xsim.dir/d_flip_flop_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/cedar/Documents/School/TAMU/2021/Autumn/ECEN 248/Laboratory Material/Lab 7/lab7/lab7.sim/sim_1/behav/xsim/xsim.dir/d_flip_flop_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
