webtalk_init -webtalk_dir /home/cedar/Documents/School/TAMU/2021/Autumn/ECEN 248/Laboratory Material/Lab 5/lab5/lab5.sim/sim_1/behav/xsim/xsim.dir/four_bit_alu_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Oct 11 11:13:19 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212050539_0_0_463" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "be5349e5-5b53-4f57-9941-c6cdaae86266" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d7579126ea894d268bbfca6e4926b88d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX(tm)-8320 Eight-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3910.245 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "7" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "36 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "6 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "100" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "21" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.49_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "201320_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2965610359 -regid "212050539_0_0_463" -xml /home/cedar/Documents/School/TAMU/2021/Autumn/ECEN 248/Laboratory Material/Lab 5/lab5/lab5.sim/sim_1/behav/xsim/xsim.dir/four_bit_alu_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/cedar/Documents/School/TAMU/2021/Autumn/ECEN 248/Laboratory Material/Lab 5/lab5/lab5.sim/sim_1/behav/xsim/xsim.dir/four_bit_alu_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/cedar/Documents/School/TAMU/2021/Autumn/ECEN 248/Laboratory Material/Lab 5/lab5/lab5.sim/sim_1/behav/xsim/xsim.dir/four_bit_alu_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
